# Generated by Django 4.2.7 on 2023-11-29 00:41

from django.db import migrations, models
import django.db.models.deletion
import manage_task.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='User name')),
                ('last_name', models.CharField(max_length=100, verbose_name='User last name')),
                ('document_type', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('CE', 'Cedula Extranjera'), ('TI', 'Tarjeta de Identidad')], max_length=2, verbose_name='Document type')),
                ('document_number', models.CharField(max_length=10, unique=True, validators=[manage_task.models.is_digit], verbose_name='Document number')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email address')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Task tittle')),
                ('description', models.TextField(verbose_name='Task description')),
                ('deadline_date', models.DateField(verbose_name='Task deadline date')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_task.person')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
