# Generated by Django 4.2.7 on 2023-11-29 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_task', '0002_alter_task_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='manage_task.person'),
        ),
    ]
