# Generated by Django 4.2.7 on 2023-12-18 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_task', '0003_alter_task_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_task.person'),
        ),
    ]
